service: node-ts-serverless

provider:
  name: aws
  runtime: nodejs22.x
  environment:
    API_VERSION: ${env:API_VERSION, 'api_v1'}
    NODE_ENV: ${env:NODE_ENV, 'staging'}
    DATABASE_URL: ${env:DATABASE_URL, 'mysql://root:password@127.0.0.1:3306/node_serverless'}

custom:
  apiPrefix: ${env:API_VERSION, 'api_v1'}

plugins:
  - serverless-offline

serverless-offline:
  httpPort: ${env:PORT, '5000'}
  apiPrefix: ${self:custom.apiPrefix}

functions:
  auth:
    handler: src/auth/authHandler.handler
    events:
      - http:
          path: ${self:custom.apiPrefix}/auth/{proxy+}
          method: any
