export const RESPONSE_MESSAGES = {
    GLOBAL: {
        NOT_FOUND: "No data found",
    },
    USER: {
        CREATED: "User created successfully",
        UPDATED: "User updated successfully",
        DELETED: "User deleted successfully",
        NOT_FOUND: "User not found",
        ALREADY_EXISTS: "User already exists",
        FETCHED: "User fetched successfully",
        FETCHED_ALL: "Users fetched successfully",
        BLOCKED: "User account is blocked",
        UPDATE_FAILED: "Failed to update user",
        DELETE_FAILED: "Failed to delete user",
        ENROLLMENT_COURSES: "User enrollment courses",
        WISHLIST_REMOVED: "User Wishlist Removed",
        WISHLIST_ADDED: "User Wishlist Added",
        WISHLIST_LIST: "User Wishlist list",
        USER_NOTIFICATION_ADDED: "User notification request added",
        USER_DETAIL: "User detail"
    },
    AUTH: {
        LOGIN_SUCCESS: "Login successful",
        LOGIN_FAILED: "Invalid credentials",
        LOGOUT_SUCCESS: "Logout successful",
        TOKEN_EXPIRED: "Token has expired",
        TOKEN_VERIFIED: "Token verified",
        TOKEN_INVALID: "Invalid token",
        TOKEN_MISSING: "Token is missing",
        TOKEN_TYPE_MISSING: "Invalid token type. Use Bearer token",
        REFRESH_TOKEN_ONLY: "Refresh tokens can only be used with the refresh-token endpoint",
        REGISTER_SUCCESS: "Registration successful",
        EMAIL_NOT_VERIFIED: "Email not verified",
        USER_ALREADY_EXISTS: "User already exists",
        ACCOUNT_SUSPENDED: "Account is suspended. Please contact support.",
        FORGOT_PASSWORD_SUCCESS: "We have sent you a link to reset your password. Please check your email.",
        INVALID_RESET_TOKEN: "Invalid reset token",
        RESET_TOKEN_EXPIRED: "Reset token has expired",
        PASSWORD_RESET_SUCCESS: "Password reset successful",
        INVALID_PASSWORD: "Invalid password",
        USER_ALREADY_EXISTS_VERIFICATION: "User already exist! Please Sign in to continue",
        MAIL_SENT_SUCCESS: "Mail sent successfully",
        EMAIL_NOT_MATCHED: "Email is not matched with any records!.",
        EMAIL_VERIFIED_SUCCESS: "Email verified successfully",
        INVALID_VERIFICATION_TOKEN: "Invalid verification token",
        USER_EMAIL_FOUND: "User email found",
        EMAIL_ALREADY_VERIFIED: "Email already verified",
        EMAIL_ALREADY_EXIST: "Email already exist",
        INACTIVE_USER: "Inactive User",
    },
    HEALTH: {
        DATABASE_CHECK_SUCCESS: "Database check successful",
        DATABASE_CHECK_FAILED: "Database check failed",
    },
    COMMON: {
        SUCCESS: "Operation successful",
        ERROR: "An error occurred",
        VALIDATION_ERROR: "Validation failed",
        UNAUTHORIZED: "Unauthorized access",
        FORBIDDEN: "Access forbidden",
        INTERNAL_SERVER_ERROR: "Internal server error",
        NOT_FOUND: "Resource not found",
        CONFLICT: "Resource conflict",
    },


} as const;